### ISSUE TITLE
Define the project:  Pitch the project back to me in a cleaned up format

### ISSUE THREAD

**Issue by danberkeland** [danberkeland/BPBWholesaleSite#1]
Below I'll do my best to define what I'm looking for in this project.  I would like to see your cleaned up pitch back to me showing your understanding of the project, the areas that interest you, and what you may be able to deliver.  I'm not looking for anything perfect, of course, just a starting point to make sure we're on the same page.  

I'm also curious to see what kinds of resources you guys use to make these types of presentations.  It will be a learning process for me, too, that I'm excited about.  You could include things like this:
- Introduce yourself, your strengths, your interests, what you'd like to learn from this
- Define the problem
- Define your solution
- What will you deliver
- What will your process look like

So here's my pitch:

- We need an application that allows our wholesale customers (restaurants, cafes, hotels, markets, etc.) to place their orders, view their billing, and manage their account settings (address, hours, etc.)
- The same application should allow the management of the Back Porch Bakery to place orders, view/print production reports, view/print logistics reports, manage invoicing, etc.
- The wholesale customer interface should be simple and accessible on a mobile.
- The administrative interface will usually be handled on a laptop but some mobile functionality would be great.
- The biggest challenge will likely be in understanding and building the database that drives all of this.
- Another challenge will be in tying the application into the APIs of other apps that we use (SquareUp, Quickbooks, Homebase, etc.)

**Comment by xzhao11** [comment]
Hi, my name is Curly Zhao and I am excited to work on this project together with you guys. I am very into web development, both the frontend design and the backend database. I take most of my database classes at school and learn most of my frontend web design skills myself. So from this project, I'd like to test and practice the skills I learned and strengthener my knowledge about databases and web design in general. I am also interested in eCommerce and how web development work in an eCommerce system. Here is my pitch:

- I can work on the frame of the website, make them modern-look and interactive, with each part integrated well. I will utilize the knowledge from my learning, as well as doing more research on how things can look and interact better on the website.

- I can also work on the database, I believe I have a solid understanding of database and what's the best data model to use to optimize performance and storage. I will take most of my time learning about what should be included in the database and the relationships, after that, the actual building of the database is fairly easy. But I do need to do more research on how to make database manageable in the cloud.

- For the integration of the APIs, I am interested but I do not have much prior knowledge of how to accomplish that, but if needed and time allows, I can definitely research on that as well.

- We should have more discussion on the scope of the work and where is the best starting point for the project. I personally can be assigned to any portion of the project.

**Comment by Hunter-Lane** [comment]
## Intro
Hello! I am Hunter Lane, a Computer Science major focusing on application development. I have spent the majority of my time as a student working on backend projects, so one thing I would like to accomplish from this is being able to connect backend models with a visually appealing and simple frontend design.

## The Problem
Existing applications do not provide the means for product suppliers to properly communicate with their clients. Supply and demand constantly changes, and an application built for this type of commerce must be able to handle these changes.

## The Solution 
Build a web application that allows for administrative users (Back Porch Bakery) to specify the available stock of products at any given time. This should be able to keep track of ongoing orders and update data accordingly. In seeing this information, clients will be able to place an order and provide their information to handle pickup / billing. Finally, Back Porch Bakery should be able to easily access these ongoing orders and mark them as completed when the transaction is complete.

## Pitch
 * The first step is going to be getting a wireframe or prototype setup so we have a general idea of how clients should go about making an order. I am not particularly clear about the process of wholesale companies making purchases through the bakery so it would be good to get a better understanding of that early on.

 * In addition, I can design the database structure that would be needed to support the necessary user interactions.
 
 * Similarly to what Curly previously mentioned, I do not have direct experience with the APIs you mentioned, but that is certainly something that can be overcome with research.
 
* Since there are multiple people interested in working on this project, I am happy to call to get a better idea of which aspects people are interested in.
